[general]
library_name = "libaeron"
library_names = {"aeronc.h" = "libaeron", "aeron_archive.h" = "libaeron_archive_c_client"}
output_file_path = "../src/LibAeron.jl"
module_name = "LibAeron"
jll_pkg_name = "Aeron_jll"
prologue_file_path = "./prologue.jl"
export_symbol_prefixes = ["aeron_", "AERON_", "ARCHIVE_"]
use_julia_native_enum_type = false
auto_mutability = false
extract_c_comment_style = "doxygen"
show_c_function_prototype = true
use_deterministic_symbol = true
smart_de_anonymize = true

output_ignorelist = [
    "aeron_counter_value_descriptor_stct",
    "aeron_counter_value_descriptor_t",
    "aeron_counter_metadata_descriptor_stct",
    "aeron_counter_metadata_descriptor_t",
    "AERON_COUNTER_VALUE_LENGTH",
    "AERON_COUNTER_METADATA_LENGTH",
    "AERON_COUNTER_MAX_LABEL_LENGTH",
    "AERON_COUNTER_MAX_KEY_LENGTH",
    "AERON_COUNTER_REGISTRATION_ID_OFFSET",
    "AERON_COUNTER_TYPE_ID_OFFSET",
    "AERON_COUNTER_FREE_FOR_REUSE_DEADLINE_OFFSET",
    "AERON_COUNTER_KEY_OFFSET",
    "AERON_COUNTER_LABEL_LENGTH_OFFSET",
]

[codegen]
use_julia_bool = true
use_ccall_macro = true
always_NUL_terminated_string = true

[codegen.macro]
macro_mode = "basic"
